export const BRAND_DATA = [
  { value: "athletix", label: "Athletix" },
  { value: "aquafast", label: "AquaFast" },
  { value: "prohoop", label: "ProHoop" },
  { value: "zenflex", label: "ZenFlex" },
  { value: "ridesafe", label: "RideSafe" },
  { value: "highrange", label: "HighRange" },
  { value: "goalmaster", label: "GoalMaster" },
  { value: "eaglestrike", label: "EagleStrike" },
  { value: "courtmaster", label: "CourtMaster" },
  { value: "fitrow", label: "FitRow" },
  { value: "flexiform", label: "FlexiForm" },
  { value: "prostroke", label: "ProStroke" },
  { value: "trailblazer", label: "TrailBlazer" },
  { value: "alpinepro", label: "AlpinePro" },
  { value: "skyhigh", label: "SkyHigh" },
  { value: "gamemaster", label: "GameMaster" },
];
